name: sijaliproject
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  http: ^1.1.0
  geolocator: ^9.0.0
  geocoding: ^2.0.4
  permission_handler: ^11.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - images/welcome.png
  - images/bg1-removebg-preview.png
  - images/kritikSaran.png
  - images/empty-image.jpg
