name: sijaliproject
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  http: ^1.1.0
  geolocator: ^10.1.0
  image: ^3.0.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  url_launcher: ^6.2.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
  - images/welcome.png
  - images/bg1-removebg-preview.png
  - images/kritikSaran.png
  - images/empty-image.jpg
  - images/tambah_kasus_batas.png
  - images/update_kasus_batas.png
  - images/notifikasi.png

